/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mp2srt.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-31-2013
 * 
 * XDoclet definition:
 * @struts.form name="adminmailerForm"
 */
public class AdminmailerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** conduition property */
	private String conduition;

	/** email property */
	private String email;

	/** organisation property */
	private String organisation;

	/** name property */
	private String name;

	/** note property */
	private String note;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the conduition.
	 * @return String
	 */
	public String getConduition() {
		return conduition;
	}

	/** 
	 * Set the conduition.
	 * @param conduition The conduition to set
	 */
	public void setConduition(String conduition) {
		this.conduition = conduition;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the organisation.
	 * @return String
	 */
	public String getOrganisation() {
		return organisation;
	}

	/** 
	 * Set the organisation.
	 * @param organisation The organisation to set
	 */
	public void setOrganisation(String organisation) {
		this.organisation = organisation;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the note.
	 * @return String
	 */
	public String getNote() {
		return note;
	}

	/** 
	 * Set the note.
	 * @param note The note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}
}