/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mp2srt.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-31-2013
 * 
 * XDoclet definition:
 * @struts.form name="readerForm"
 */
public class ReaderForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** idmail property */
	private String idmail;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the idmail.
	 * @return String
	 */
	public String getIdmail() {
		return idmail;
	}

	/** 
	 * Set the idmail.
	 * @param idmail The idmail to set
	 */
	public void setIdmail(String idmail) {
		this.idmail = idmail;
	}
}