/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mp2srt.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-02-2014
 * 
 * XDoclet definition:
 * @struts.form name="vocalmanForm"
 */
public class VocalmanForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** index property */
	private String index;

	/** vocab property */
	private String vocab;

	/** user property */
	private String user;

	/** man property */
	private String man;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the index.
	 * @return String
	 */
	public String getIndex() {
		return index;
	}

	/** 
	 * Set the index.
	 * @param index The index to set
	 */
	public void setIndex(String index) {
		this.index = index;
	}

	/** 
	 * Returns the vocab.
	 * @return String
	 */
	public String getVocab() {
		return vocab;
	}

	/** 
	 * Set the vocab.
	 * @param vocab The vocab to set
	 */
	public void setVocab(String vocab) {
		this.vocab = vocab;
	}

	/** 
	 * Returns the user.
	 * @return String
	 */
	public String getUser() {
		return user;
	}

	/** 
	 * Set the user.
	 * @param user The user to set
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/** 
	 * Returns the man.
	 * @return String
	 */
	public String getMan() {
		return man;
	}

	/** 
	 * Set the man.
	 * @param man The man to set
	 */
	public void setMan(String man) {
		this.man = man;
	}
}