/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mp2srt.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.swing.text.TextAction;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.mp2srt.hibernate.HibernateSessionFactory;
import com.mp2srt.hibernate.Vocabulaire;
import com.mp2srt.hibernate.VocabulaireDAO;
import com.mp2srt.struts.form.ManagevocabForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-02-2014
 * 
 * XDoclet definition:
 * @struts.action path="/managevocab" name="managevocabForm" input="/superviser.jsp" scope="request" validate="true"
 * @struts.action-forward name="remove" path="/superviser.jsp" redirect="true"
 * @struts.action-forward name="addvocab" path="/addvocab.jsp" redirect="true"
 * @struts.action-forward name="editvocab" path="/editvocab.jsp" redirect="true"
 */
public class ManagevocabAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ManagevocabForm managevocabForm = (ManagevocabForm) form;// TODO Auto-generated method stub
		
		String edit= managevocabForm.getEdit();
		String output="remove";
		Logger log = Logger.getLogger(TextAction.class);

		
		VocabulaireDAO vocdao = new VocabulaireDAO();
		Vocabulaire voc = new Vocabulaire();
		long id;
		String index;
		
		if (edit.contains("Delete")){
			index = (String) edit.subSequence(7, edit.length());
			id = Long.parseLong(index);
			voc = vocdao.findById(id);
			
			Session hsf = HibernateSessionFactory.getSession();
			Transaction trans = hsf.beginTransaction();
			hsf.delete(voc); 
			trans.commit();
			hsf.close();
			
			output="remove";
			request.getSession().setAttribute("info", "The vocabulary has been deleted.");
			log.info("The vocabulary with the id " + voc.getIdVocab() + " has been deleted.");
		}
		
		else if (edit.contains("Add")){
			output="addvocab";
		}
		
		else if (edit.contains("Edit")){
			index = (String) edit.subSequence(5, edit.length());
			id = Long.parseLong(index);
			voc = vocdao.findById(id);
			
			
			request.getSession().setAttribute("index", index);
			request.getSession().setAttribute("user", voc.getCompte());
			request.getSession().setAttribute("vocab", voc.getNomVocab());
			
			output="editvocab";
		}
		
		return mapping.findForward(output);
	}
}